name: WebDriverIO Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22' # Set the Node.js version you need

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          npm install

      # Step 4: Set up Chrome
      - name: Set up Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      # Step 5: Install ChromeDriver
      - name: Install ChromeDriver
        run: |
          sudo apt-get install -y chromium-chromedriver
          
      - name: Fix permissions for wdio
        run: chmod +x node_modules/.bin/wdio
          
      # Step 6: Run WebDriverIO tests
      - name: Run WebDriverIO tests
        run: |
             npm run wdio
